config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  root 'users#index'
  resources :users

  # Example 1 :- Root Routes.
  # root "users#index"
  # root to: 'users#index'

  # Example 2 :- as method change the path name
  # get 'exit', to: 'sessions#destroy'
  # get 'exit', to: 'sessions#destroy', as: :logout

  # Example 3 :- Redirect Path Example
  # resources :posts
  # get '/blogs', to: redirect('https://www.google.co.uk/')
  # get '/blogs/new', to: redirect('/posts/new')

  # Example 4 :- Format
  # namespace :api do
  #   namespace :v1 do
  #     resources :blogs, defaults: { format: :json }
  #   end
  # end

  # Example 5 :- Resources Routes.
  # Example 1
  # resources :photos, :posts
  # Example 2
  # resources :books
  # resources :video

  # Example 6 :- Resource with specific routes
  # resources :blogs, only: [:index, :show]

  # Example 7 :- Resource with different controller.
  # resources :blogs, controller: 'users'

  # Example 8 :- Collection routes.
  # Define first way
  # resources :blogs do
  # 	collection do
  # 		get 'search'
  # 	end
  # end

  # Define Second Way
  # resources :blogs do
  # 	get 'search', on: :collection
  # end

  # Blog Shallow Nested Routes Example
  # Namespace Routes
  # namespace :admin do
  #   resource :super_admin, :plans
  # end

  # Namespace Scope Routes
  # Scope With Module
  # Define first way
  # scope module: 'admin' do
  #   resources :super_admin, :plans
  # end

  # Define Second way
  # resource :super_admin, :plans, module: 'admin'

  # Define scope
  # scope '/admin' do
  # 	resources :super_admin
  # end

  # ShallowRoutes
  # resources :users, :shallow => true do
  #   resources :posts
  # end

  # Load External Routes file routes_concern.rb
  draw :routes_concern


  # Rails Routes Constraints
  # 1. Regular Expression
  resources :products, only: [:index, :new, :edit, :update, :destroy]
  get 'products/:id', to: 'products#show', as: :show_product, constraints: { id: /\d+/ }

  # 2.HTTP Verb Constraints
  match '/products/:id', to: 'products#update', via: [:put, :patch]

  # 3. Request based Constraints
  # Example 1 
    constraints LangVerifyConstraint.new do 
      get 'hello', to: 'greetings#hindi'
    end
    get 'hello', to: 'greetings#english'
  
  # Example 2: API VERSION
  # Version 1 - Mobile and Desktop
    constraints ApiVersionConstraint.new('v1') do 
      # If this fails then it will Rails moves to the next matching route in the routing table. 
      get 'api/v1/users', to: 'api/v1/users#index_v1'
    end 

  # Version 2 - Mobile and Desktop
    constraints(ApiVersionConstraint.new('v2')) do
      get 'api/v2/users', to: 'api/v2/users#index'
    end

  # Fallback if no version matches (default v1)
    get 'api/v1/users', to: 'api/v1/users#old_customer'
    get 'api/v2/users', to: 'api/v2/users#old_customer'

  # 4. Advance Constraints
    # Example 1 Blocking Fake Orders Based on Order Frequency (Rate Limiting)
      resources :orders, only: [:index, :new, :edit, :update, :show, :destroy]

      # constraints SuspiciousEmailConstraint.new do
      #   post 'orders', to: 'orders#create' 
      # end 

    # Fallback route for suspicious emails
    # post 'orders', to: 'orders#suspicious_email'

    # Example 2 Blocking Fake Orders Based on Order Frequency (Rate Limiting)
    # constraints RateLimitConstraint.new do
    #   post 'orders', to: 'orders#create'
    # end 

    # Fallback route for suspicious emails
    # post 'orders', to: 'orders#rate_limit_exceeded'

    # Example 3 Blocking Fake Orders Based on Excessive Quantity
      constraints QuantityLimitConstraint.new do
        post 'orders', to: 'orders#create'
      end 

    # Fallback route for suspicious emails
    post 'orders', to: 'orders#order_qty__limit_exceeded'

  # 4. Rails Uniq routes
  # Rake Exmple
  get '/rack_app', to: MyRackApp.new

end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :compare_at, :description)
    end
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :compare_at, style: "display: block" %>
    <%= form.text_field :compare_at %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Compare at:</strong>
    <%= product.compare_at %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", show_product_path(product) %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>